### ISSUE TITLE
Summary of differences with Juerd's version

### ISSUE THREAD

**Issue by mitra42** [ESPresense/AsyncWiFiSettings#7]
Hi - @DTTerastar  - I see you've forked this from Juerd's version.

I was wondering if you could add a summary of the differences to the README ?  (or somewhere else) 

I'm asking because I've hit a few minor problems/issues with Juerd's (otherwise excellent) library, and it seems you may have tackled them - I've handled most through the callbacks which work quite well, but I think I see you asynchronously checking for the WiFi connection which is something you may have handled better than me. 

I'm asking because there was a minor issue I was going to raise on @Juerd's repo, but none of the recent issues seem to have been responded for in about a year or so, (which is entirely reasonable, and I'm grateful for his library) so it might make more sense to work/contribute to an actively maintained fork.

**Comment by DTTerastar** [comment]
The main difference is the webpages use a totally different library (an async one)
